name: flutter_app
description: "A new Flutter project for flower shop"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  supabase_flutter: ^2.1.2
  image_picker: ^1.0.4   # Для выбора изображения из галереи
  photo_view: ^0.14.0    # Для красивого приближения изображения букета
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
